# list of packages used by the scripts from the EXOFISHMED project

cran_packages   <- c(
                     "phyloseq",                     
                     "ggplot2",
                     "microbiome", 
                     "tidyverse",                     
                     "vegan", 
                     "dplyr",                 
                     "ggrepel", 
                     "R.utils", 
                     "devtools",
                     "sys",
                     "reshape2", 
                     "devtools", 
                     "PMA",
                     "ade4", 
                     "ape",
                     "Biostrings", 
                     "picante",
                     "abind",
                     "Matrix",
                     "ecodist",
                     "mda",
                     "compositions", 
                     "klaR",
                     "PVR",
                     "randomcoloR",
                     "MicEco",
                     "labdsv",
                     "epitools",
                     "adephylo",
                     "readxl",
                     "lmerTest",
                     "MuMIn",
                     "car",
                     "kableExtra",
                     "ape",
                     "ade4",
                     "entropart"
)


bioc_packages   <- c("phyloseq", 
                     "genefilter", 
                     "impute", 
                     "dada2", 
                     "DECIPHER", 
                     "microbiome",
                     "ggtree",
                     "RCy3")
